renamed expand.sh -> s3-expand

diff --git a/tests/expand-env/expand-env b/tests/expand-env/expand-env
--- a/tests/expand-env/expand-env
+++ b/tests/expand-env/expand-env
@@ -16,9 +16,9 @@ export PERMSE="Mice upon a time..."
 
 
 test_succeeded=true
-if ! ../../expand.sh true; then # start expand.sh test
+if ! ../../s3-expand true; then # start s3-expand test
   test_succeeded=false
-  echo "ERROR: expand.sh failed"
+  echo "ERROR: s3-expand failed"
 else
 
 
@@ -178,5 +178,5 @@ elif ! [[ $PERMSE == $(<./perms5) ]]; then
 	EOF
 fi
 
-fi # end expand.sh test
+fi # end s3-expand test
 $test_succeeded
diff --git a/tests/expand-sed/expand-sed b/tests/expand-sed/expand-sed
--- a/tests/expand-sed/expand-sed
+++ b/tests/expand-sed/expand-sed
@@ -29,9 +29,9 @@ sed -i checkfileB -f sedB
 
 
 
-if ! ../../expand.sh true; then
+if ! ../../s3-expand true; then
   test_succeeded=false
-  echo "ERROR: expand.sh exited."
+  echo "ERROR: s3-expand exited."
 else
   # Check File Creation
   for file in sedA sedB testfileA testfileB checkfileA checkfileB; do
diff --git a/tests/s3-files/s3-files b/tests/s3-files/s3-files
--- a/tests/s3-files/s3-files
+++ b/tests/s3-files/s3-files
@@ -9,9 +9,9 @@ if . ../check-s3-creds; then
 
   export EXPAND_S3_FILES="$S3_TEST_PATH/testfileA|./fileA $S3_TEST_PATH/testfileB|./newdir/fileB |./nonexist1 $S3_TEST_PATH/nonexist2| $S3_TEST_PATH/nonexist3"
 
-  if ! ../../expand.sh true; then
+  if ! ../../s3-expand true; then
     test_succeeded=false
-    echo "ERROR: expand.sh exited."
+    echo "ERROR: s3-expand exited."
   else
     # Check File Creation
     for file in ./fileA ./newdir ./newdir/fileB; do
diff --git a/tests/s3-sync/s3-sync b/tests/s3-sync/s3-sync
--- a/tests/s3-sync/s3-sync
+++ b/tests/s3-sync/s3-sync
@@ -7,9 +7,9 @@ if . ../check-s3-creds; then
 
   export EXPAND_S3_FOLDERS="$S3_TEST_PATH/s3-sync/|./comparedir $S3_TEST_PATH/s3-sync/|./newdir/comparedir $S3_TEST_PATH/s3-sync|./parent  $S3_TEST_PATH/s3-sync|./newdir/parent |./nonexist1 $S3_TEST_PATH/nonexist2| $S3_TEST_PATH/nonexist3 $S3_TEST_PATH/nonexist4/| $S3_TEST_PATH/nonexist5/"
 
-  if ! ../../expand.sh true; then
+  if ! ../../s3-expand true; then
     test_succeeded=false
-    echo "ERROR: expand.sh exited."
+    echo "ERROR: s3-expand exited."
   else
     # Check File Creation
     for file in ./comparedir ./newdir ./newdir/comparedir ./parent ./newdir/parent; do
diff --git a/tests/s3-tars/s3-tars b/tests/s3-tars/s3-tars
--- a/tests/s3-tars/s3-tars
+++ b/tests/s3-tars/s3-tars
@@ -10,9 +10,9 @@ if . ../check-s3-creds; then
 
   export EXPAND_S3_TARS="$S3_TEST_PATH/s3-tars.tar|./comparedir $S3_TEST_PATH/s3-tars.tar|./newdir/comparedir |./nonexist1 $S3_TEST_PATH/nonexist2.tar| $S3_TEST_PATH/nonexist3"
 
-  if ! ../../expand.sh true; then
+  if ! ../../s3-expand true; then
     test_succeeded=false
-    echo "ERROR: expand.sh exited."
+    echo "ERROR: s3-expand exited."
   else
     # Check File Creation
     for file in ./comparedir ./newdir ./newdir/comparedir ; do
